version: '3'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - api
    networks:
      - chat
    env_file:
      - ./web/.env
    environment:
      - BACKEND_URL=http://api:8081
      - WEB_PORT=8888
      - WEB_HOST=0.0.0.0
      # Add this to your .env file
      # NEW_RELIC_LICENSE_KEY=123

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - chat
    env_file:
      - ./api/.env
    environment:
      - REDIS_BASE=redis://db:6379/0
      - PINECONE_NAMESPACE=default
      - PINECONE_REGION=us-east-1
    # Add these to your .env file
    # OPENAI_API_KEY=sk-proj-123
    # PINECONE_API_KEY=123
    # NEW_RELIC_LICENSE_KEY=123

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - chat
    ports:
      - 6379:6379

  # monitoring:
  #   container_name: newrelic-infra
  #   build:
      # context: ./monitoring
      # dockerfile: Dockerfile
  #   cap_add:
  #     - SYS_PTRACE
  #   pid: host
  #   privileged: true
  #   volumes:
  #     - "/:/host:ro"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   restart: unless-stopped
  #   networks:
  #     - chat
  #   env_file:
  #     - ./monitoring/.env
  #    Add this to your .env file
  #    NEW_RELIC_LICENSE_KEY=123

networks:
  chat:
    driver: bridge
