version: '3'

# Add these to your .env file
# OPENAI_API_KEY=sk-proj-123
# PINECONE_API_KEY=123
# NEW_RELIC_LICENSE_KEY=123
# See .env.example for reference

services:
  web:
    image: nullstring/ai-chat-demo-web
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - api
    networks:
      - chat
    env_file:
      - ../.env
    environment:
      - BACKEND_URL=http://api:8081
      - WEB_PORT=8888
      - WEB_HOST=0.0.0.0

  api:
    image: nullstring/ai-chat-demo-api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - chat
    env_file:
      - ../.env
    environment:
      - REDIS_BASE=redis://db:6379/0
      - PINECONE_NAMESPACE=default
      - PINECONE_REGION=us-east-1

  db:
    image: redis:alpine3.18
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - chat
    ports:
      - 6379:6379

networks:
  chat:
    driver: bridge
